name: Documentation 

on:
  push:
    branches: [ main ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get install libeigen3-dev -y
        sudo apt-get install clang -y
        sudo apt-get install doxygen -y
        sudo apt-get install graphviz -y
      
    - name: Build documentation
      working-directory: ${{ github.workspace }}
      run: docs/builddocs.sh

    - name: Deploy documentation
      working-directory: ${{ github.workspace }}
      run: docs/deploydocs.sh